version: "3.3"
services:
  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=testdb
      - MONGO_INITDB_USERNAME=mongo
      - MONGO_INITDB_PASSWORD=12345

  app:
    image: app
    ports:
      - 8080:8080
    container_name: app
    links:
      - mongo
    entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"