FROM openjdk:11-jre-slim
MAINTAINER "Docker App <docker@app.com>"
WORKDIR /app

COPY ./target/*.jar ./app.jar
ENTRYPOINT ["java", "-jar", "/app/app.jar"]

EXPOSE 8080


FROM openjdk:8-windowsservercore
LABEL maintainer="sevil.toprak@hotmail.com.com"

COPY ./target/*.jar ./app.jar
EXPOSE 8080

CMD ["java", "-jar", "demo.jar"]
